# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devnoob', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, upload_to=b'devnoob/static/img/portfolio')),
                ('link', models.URLField()),
                ('conteudo', models.TextField()),
            ],
        ),
    ]
