# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devnoob', '0004_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('nivel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gosto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=300)),
                ('telefone', models.CharField(max_length=15)),
                ('foto_perfil', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('servicos', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recomendacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('conteudo', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='imagem',
            field=models.CharField(max_length=200),
        ),
    ]
