# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-09 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devnoob', '0005_auto_20171104_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(upload_to='perfies'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='imagem',
            field=models.ImageField(upload_to='portfolio'),
        ),
    ]
